### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by ZhongBaode** [open-rmf/rmf#113]
### Required information:

- Operating system and version:
  Ubuntu 20.04
- OpenRMF installation type:
  - 
  From [main branch's](https://github.com/open-rmf/rmf) binary install 
- OpenRMF version or commit hash
  - 
  Main branch version
  
- ROS distribution and version:
  - 
- ROS installation type: Foxy
  - 
- Package or library, if applicable:  Binary install
  - 

### Description of the bug

Followed the installation guide of building from source and during colcon build, spits out an error,
```
/home/rosi/rmf_ws/src/rmf/rmf_ros2/rmf_fleet_adapter/src/rmf_fleet_adapter/agv/parse_graph.cpp: In function ‘rmf_traffic::agv::Graph rmf_fleet_adapter::agv::parse_graph(const string&, const rmf_traffic::agv::VehicleTraits&)’:
/home/rosi/rmf_ws/src/rmf/rmf_ros2/rmf_fleet_adapter/src/rmf_fleet_adapter/agv/parse_graph.cpp:297:20: error: ‘class rmf_traffic::agv::Graph::Lane’ has no member named ‘properties’
  297 |         graph_lane.properties().speed_limit(speed_limit);
```

The package that failed is rmf_fleet_adapter:
```
Failed   <<< rmf_fleet_adapter
```

### Steps to reproduce the bug
Follow the installation guide of building from source

**Comment by youliangtan** [comment]
Would like to direct this issue to the related discussion here: https://github.com/open-rmf/rmf/discussions/112

**Comment by ZhongBaode** [comment]
Okay thanks very much!
