### ISSUE TITLE
Missing dependency in building from source

### ISSUE THREAD

**Issue by halodluc** [open-rmf/rmf#249]
### Required information:

- Operating system and version:
  -  Ubuntu 22
- OpenRMF installation type:
  -  from source: https://github.com/open-rmf/rmf#building-from-sources
- OpenRMF version or commit hash
  -  https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
- ROS distribution and version:
  -  rolling
- ROS installation type:
  -  binaries

### Description of the bug

I followed the installation from source tutorial: https://github.com/open-rmf/rmf#building-from-sources and the colcon build phase crashed on the package rmf_api_msgs with the message No module named 'datamodel_code_generator'. I fixed it with pip install datamodel_code_generator.

**Comment by Yadunund** [comment]
Fixed by https://github.com/open-rmf/rmf/pull/250
