### ISSUE TITLE
Extend rosdep keys upstream

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf#27]
RMF packages require certain python dependencies to be installed manually. It would be beneficial for users building from source and also during binary generation, if these dependencies can be installed automatically via `rosdep`. They include:
* python3-shapely
* python3-yaml
* python3-requests
* python3-flask-cors

**Comment by tanyouliang95** [comment]
Yes, we can use `rosdep` as it is specified in https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml. I will address this, and append this dep on its relevant `package.xml`.
