### ISSUE TITLE
RMF Humble build is failing -colcon build --mixin release lld

### ISSUE THREAD

**Issue by shyamkris** [open-rmf/rmf#288]
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/usr/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/user/rmf_ws/build/rmf_fleet_msgs/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_f467a/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_f467a.dir/build.make CMakeFiles/cmTC_f467a.dir/build
    gmake[1]: Entering directory '/home/user/rmf_ws/build/rmf_fleet_msgs/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_f467a.dir/testCXXCompiler.cxx.o
    /usr/bin/clang++    -MD -MT CMakeFiles/cmTC_f467a.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_f467a.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_f467a.dir/testCXXCompiler.cxx.o -c /home/user/rmf_ws/build/rmf_fleet_msgs/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    Linking CXX executable cmTC_f467a
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f467a.dir/link.txt --verbose=1
    /usr/bin/clang++ -fuse-ld=lld  CMakeFiles/cmTC_f467a.dir/testCXXCompiler.cxx.o -o cmTC_f467a 
    ld.lld: error: unable to find library -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gmake[1]: *** [CMakeFiles/cmTC_f467a.dir/build.make:100: cmTC_f467a] Error 1
    gmake[1]: Leaving directory '/home/user/rmf_ws/build/rmf_fleet_msgs/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_f467a/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

**Comment by xiyuoh** [comment]
Hi, you can try `sudo apt install g++-12` (solution referenced from [here](https://askubuntu.com/questions/1441844/todays-ubuntu-22-04-updates-seem-to-break-clang-compiler)), it worked for me

**Comment by shyamkris** [comment]
It worked. Thank you @xiyuoh

**Comment by mabasith** [comment]
Unable to locate package g++-12, ubundu 20.4, galactic

**Comment by aaronchongth** [comment]
Hello @mabasith! For ubuntu 20.04 and ROS 2 Galactic, please check the documentations under the `galactic` branch, as well as any existing issues regarding it, for example, https://github.com/open-rmf/rmf/issues/322

Please note that ROS 2 Galactic is EOL, https://docs.ros.org/en/galactic/index.html, so we would suggest moving to ROS 2 Humble on Ubuntu 22.04 to enjoy the latest features.
