### ISSUE TITLE
Robot has no task but received path to move

### ISSUE THREAD

**Issue by mbb1234567890** [open-rmf/rmf#292]
when server start and add robot success, their is no task but console logs WARN regularly like :
`

> [schedule_visualizer_node-4] [WARN] [1672669567.111044163] [schedule_data_node]: Failed to update using patch for DB version 240 (mirror version: none, patch base: 239); requesting new update
[schedule_visualizer_node-4] [INFO] [1672669567.111071838] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history

`
and then received new path with current point
log details bellow:

`

> [fleet_adapter-14] 2023-01-02 14:19:04.941 line76 INFO Received UpdateRobotState: name: "glRobot2"
[fleet_adapter-14] task_id: "6"
[fleet_adapter-14] battery_percent: 100
[fleet_adapter-14] location {
[fleet_adapter-14]   x: 20.063438309814579
[fleet_adapter-14]   y: -13.9996413902849
[fleet_adapter-14]   approach_speed_limit: 0.5
[fleet_adapter-14]   level_name: "L1"
[fleet_adapter-14] }
[fleet_adapter-14] mode {
[fleet_adapter-14]   mode_request_id: 2
[fleet_adapter-14] }
[fleet_adapter-14] sequence: 1
[fleet_adapter-14] 
[fleet_adapter-14] 2023-01-02 14:19:05.949 line76 INFO Received UpdateRobotState: name: "glRobot1"
[fleet_adapter-14] task_id: "6"
[fleet_adapter-14] battery_percent: 100
[fleet_adapter-14] location {
[fleet_adapter-14]   x: 18.461529406570712
[fleet_adapter-14]   y: -20.885378778243371
[fleet_adapter-14]   approach_speed_limit: 0.5
[fleet_adapter-14]   level_name: "L1"
[fleet_adapter-14] }
[fleet_adapter-14] mode {
[fleet_adapter-14]   mode_request_id: 2
[fleet_adapter-14] }
[fleet_adapter-14] sequence: 1
[fleet_adapter-14] 
[fleet_adapter-14] 2023-01-02 14:19:05.956 line76 INFO Received UpdateRobotState: name: "glRobot2"
[fleet_adapter-14] task_id: "6"
[fleet_adapter-14] battery_percent: 100
[fleet_adapter-14] location {
[fleet_adapter-14]   x: 20.063438309814579
[fleet_adapter-14]   y: -13.9996413902849
[fleet_adapter-14]   approach_speed_limit: 0.5
[fleet_adapter-14]   level_name: "L1"
[fleet_adapter-14] }
[fleet_adapter-14] mode {
[fleet_adapter-14]   mode_request_id: 2
[fleet_adapter-14] }
[fleet_adapter-14] sequence: 1
[fleet_adapter-14] 
[schedule_visualizer_node-4] [WARN] [1672669146.598111625] [schedule_data_node]: Failed to update using patch for DB version 49 (mirror version: none, patch base: 48); requesting new update
[schedule_visualizer_node-4] [INFO] [1672669146.598268480] [schedule_data_node]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[fleet_adapter-14] [WARN] [1672669146.598355878] [GingerLite_fleet_adapter]: Failed to update using patch for DB version 49 (mirror version: none, patch base: 48); requesting new update
[fleet_adapter-14] [INFO] [1672669146.598494289] [GingerLite_fleet_adapter]: [rmf_traffic_ros2::MirrorManager::request_update] Requesting changes for query ID [1] since beginning of recorded history
[fleet_adapter-14] [INFO] [1672669146.598771060] [GingerLite_command_handle]: Received new path for glRobot2
[fleet_adapter-14] follow_new_path for glRobot2 with PlanId 6
[fleet_adapter-14] Interrupting glRobot2 (latest cmd_id is 6)
[fleet_adapter-14] Issuing cmd_id for glRobot2: 7
[fleet_adapter-14] 2023-01-02 14:19:06.607 line116 INFO DedicatedServerClient: robot_navigate, path_info="{\n  \"robot_name\": \"glRobot2\",\n  \"fleet_name\": \"GingerLite\",\n  \"task_id\": \"7\",\n  \"locations\": [\n    {\n      \"t\": {\n        \"sec\": 0,\n        \"nanosec\": 0\n      },\n      \"x\": 20.06343830981458,\n      \"y\": -13.9996413902849,\n      \"level_name\": \"L1\",\n      \"yaw\": 0.0,\n      \"obey_approach_speed_limit\": false,\n      \"approach_speed_limit\": 0.0,\n      \"index\": \"0\"\n    },\n    {\n      \"t\": {\n        \"sec\": 1672669146,\n        \"nanosec\": 605540957\n      },\n      \"x\": 20.06343830981458,\n      \"y\": -13.9996413902849,\n      \"level_name\": \"L1\",\n      \"yaw\": 0.0,\n      \"obey_approach_speed_limit\": false,\n      \"approach_speed_limit\": 0.0,\n      \"index\": \"0\"\n    }\n  ]\n}"
[rmf_traffic_schedule-1] [INFO] [1672669146.607942722] [rmf_traffic_schedule_primary]: [ScheduleNode::update_mirrors] Sending remedial update starting from the beginning going to 49 for query 1
[fleet_adapter-14] 2023-01-02 14:19:06.611 line331 INFO FleetManager: Sending navigate request for robot_name: glRobot2: cmd_id: 7, response : 
[fleet_adapter-14] 2023-01-02 14:19:06.612 line76 INFO RobotAPI: navigate_rsp= {
[fleet_adapter-14]     "success": true,
[fleet_adapter-14]     "msg": ""
[fleet_adapter-14] }
[fleet_adapter-14] [INFO] [1672669146.662436626] [GingerLite_command_handle]: Received new path for glRobot1
[fleet_adapter-14] follow_new_path for glRobot1 with PlanId 6
[fleet_adapter-14] Interrupting glRobot1 (latest cmd_id is 6)
[fleet_adapter-14] Issuing cmd_id for glRobot1: 7
[fleet_adapter-14] 2023-01-02 14:19:06.665 line116 INFO DedicatedServerClient: robot_navigate, path_info="{\n  \"robot_name\": \"glRobot1\",\n  \"fleet_name\": \"GingerLite\",\n  \"task_id\": \"7\",\n  \"locations\": [\n    {\n      \"t\": {\n        \"sec\": 0,\n        \"nanosec\": 0\n      },\n      \"x\": 18.461529406570712,\n      \"y\": -20.88537877824337,\n      \"level_name\": \"L1\",\n      \"yaw\": 0.0,\n      \"obey_approach_speed_limit\": false,\n      \"approach_speed_limit\": 0.0,\n      \"index\": \"0\"\n    },\n    {\n      \"t\": {\n        \"sec\": 1672669146,\n        \"nanosec\": 663475043\n      },\n      \"x\": 18.461529406570712,\n      \"y\": -20.88537877824337,\n      \"level_name\": \"L1\",\n      \"yaw\": 0.0,\n      \"obey_approach_speed_limit\": false,\n      \"approach_speed_limit\": 0.0,\n      \"index\": \"0\"\n    }\n  ]\n}"
[fleet_adapter-14] 2023-01-02 14:19:06.668 line331 INFO FleetManager: Sending navigate request for robot_name: glRobot1: cmd_id: 7, response : 
[fleet_adapter-14] 2023-01-02 14:19:06.669 line76 INFO RobotAPI: navigate_rsp= {
[fleet_adapter-14]     "success": true,
[fleet_adapter-14]     "msg": ""
[fleet_adapter-14] }
[fleet_adapter-14] 2023-01-02 14:19:06.965 line76 INFO Received UpdateRobotState: name: "glRobot1"
[fleet_adapter-14] task_id: "7"
[fleet_adapter-14] battery_percent: 100
[fleet_adapter-14] location {
[fleet_adapter-14]   x: 18.461529406570712
[fleet_adapter-14]   y: -20.885378778243371
[fleet_adapter-14]   approach_speed_limit: 0.5
[fleet_adapter-14]   level_name: "L1"
[fleet_adapter-14] }
[fleet_adapter-14] mode {
[fleet_adapter-14]   mode_request_id: 2
[fleet_adapter-14] }
[fleet_adapter-14] sequence: 1
[fleet_adapter-14] 
[fleet_adapter-14] 2023-01-02 14:19:06.966 line572 INFO FleetManager: Detecting completed request for 7:
[fleet_adapter-14] 2023-01-02 14:19:06.972 line76 INFO Received UpdateRobotState: name: "glRobot2"
[fleet_adapter-14] task_id: "7"
[fleet_adapter-14] battery_percent: 100
[fleet_adapter-14] location {
[fleet_adapter-14]   x: 20.063438309814579
[fleet_adapter-14]   y: -13.9996413902849
[fleet_adapter-14]   approach_speed_limit: 0.5
[fleet_adapter-14]   level_name: "L1"
[fleet_adapter-14] }
[fleet_adapter-14] mode {
[fleet_adapter-14]   mode_request_id: 2
[fleet_adapter-14] }
[fleet_adapter-14] sequence: 1
[fleet_adapter-14] 

`

**Comment by Yadunund** [comment]
See https://github.com/open-rmf/rmf/discussions/296
