### ISSUE TITLE
Build failure on Ubuntu 20.04 and Galactic when running "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

### ISSUE THREAD

**Issue by Snorlax104** [open-rmf/rmf#322]
## Bug report
Getting the following error while building the RMF source using "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

Starting >>> rmf_obstacle_msgs                                              
--- stderr: ros_ign_gazebo                                                  
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "Findignition-transport10.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-transport10", but CMake did not find one.

  Could not find a package configuration file provided by
  "ignition-transport10" with any of the following names:

    ignition-transport10Config.cmake
    ignition-transport10-config.cmake

  Add the installation prefix of "ignition-transport10" to CMAKE_PREFIX_PATH
  or set "ignition-transport10_DIR" to a directory containing one of the
  above files.  If "ignition-transport10" provides a separate development
  package or SDK, be sure it has been installed.

---
Failed   <<< ros_ign_gazebo [1.33s, exited with code 1]

### Required information:

- Operating system and version:
-Ubuntu 20.04
- OpenRMF installation type:
 -Source 
- OpenRMF version or commit hash
  - version 21.09 - https://github.com/open-rmf/rmf/tree/release/21.09
- ROS distribution and version:
 Galactic - https://docs.ros.org/en/galactic/Installation/Ubuntu-Install-Debians.html
- ROS installation type:
  binaries

### Description of the bug

--- stderr: ros_ign_gazebo                                                  
CMake Error at CMakeLists.txt:32 (find_package):
  By not providing "Findignition-transport10.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-transport10", but CMake did not find one.

  Could not find a package configuration file provided by
  "ignition-transport10" with any of the following names:

    ignition-transport10Config.cmake
    ignition-transport10-config.cmake

  Add the installation prefix of "ignition-transport10" to CMAKE_PREFIX_PATH
  or set "ignition-transport10_DIR" to a directory containing one of the
  above files.  If "ignition-transport10" provides a separate development
  package or SDK, be sure it has been installed.

**Comment by aaronchongth** [comment]
Thanks for bringing this up, there seems have been some possible changes that didn't allow `rosdep` to pull in everything that was needed. I managed to build everything on a fresh ubuntu:20.04 docker image after installing these manually,

```bash
sudo apt install ros-galactic-gazebo-ros* ros-galactic-gazebo-dev ignition-fortress
```

**Comment by aaronchongth** [comment]
Please note that ROS 2 Galactic is EOL, we would suggest upgrading to 22.04, get the latest and greatest from ROS 2 Humble, and our much newer and stable release `22.09`.

For this issue, it might be due to rosdep for Galactic not being updated over time.

Using the docker image `ros:galactic-ros-base-focal`, I needed this command

```bash
# note that i use -yr, this continues installing even after a missing package
# this should install libceres-dev, and resolve this
rosdep install --from-paths src --ignore-src --rosdistro galactic -yr

sudo apt install \
  ros-galactic-gazebo-ros* \
  ros-galactic-gazebo-dev \
  ignition-fortress \
  ros-galactic-rviz-common \
  ros-galactic-rviz-default-plugins
```

I will be closing this issue as we would highly encourage users to move to ROS 2 Humble on Ubuntu 22.04, and use the release 22.09.

**Comment by mabasith** [comment]
ld.lld: error: unable to find library -lnlohmann_json_schema_validator, Ubundu 20.04, Galactic

**Comment by aaronchongth** [comment]
@mabasith looks like this could be the solution, https://github.com/open-rmf/rmf/issues/281#issuecomment-1338884007
