### ISSUE TITLE
Build error(Failed   <<< rmf_traffic_ros2 [1min 29s, exited with code 2])

### ISSUE THREAD

**Issue by Alexander-ph** [open-rmf/rmf#345]
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- Open-RMF installation type:
  -  https://git.lejurobot.com/rmf/rmf-all.git
- Open-RMF version or commit hash
  - 21.09
- ROS distribution and version:
  - Galactic
- ROS installation type:
  - from source

### Description of the bug
When I run 'colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release', I get a build error.  You can see the error code in the screen shot below.

### Steps to reproduce the bug
1. Install ubuntu 20.04
2. Install ROS Galactic
3. install rmf for Galactic from https://git.lejurobot.com/rmf/rmf-all.git
4. When I run 'colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release', I get this build error. 

### Expected behavior
build successfully

### Actual behavior
build error

### Screenshots

![image](https://user-images.githubusercontent.com/78163172/236626476-75b1e2e7-bd38-49dc-914c-0fb0450a9580.png)

**Comment by aaronchongth** [comment]
Hello @Alexander-ph! Sorry that you're facing this, in the future please share the logs via a gist.github.com, it helps us look at the entire build process. Also just a note, we are no longer actively maintaining the galactic release, as ROS 2 Galactic is already EOL. You'll get all the nice and shiny features in ROS 2 Humble on Ubuntu 22.04 :sparkles: 

It appears that the file you are attempting to share is not available for public viewing. Please check the permissions

**Comment by Alexander-ph** [comment]
> Hello @Alexander-ph! Sorry that you're facing this, in the future please share the logs via a gist.github.com, it helps us look at the entire build process. Also just a note, we are no longer actively maintaining the galactic release, as ROS 2 Galactic is already EOL. You'll get all the nice and shiny features in ROS 2 Humble on Ubuntu 22.04 ✨
> 
> It appears that the file you are attempting to share is not available for public viewing. Please check the permissions

sorry，I did not save it :). 
sorry for that, I'm just starting to learn this. 
And, I'm just a new member for that repository, I have no right.

**Comment by aaronchongth** [comment]
No problems at all! Without knowing the exact releases that are being built, I'm afraid we are unable to help much other than advising to migrate to ROS 2 Humble's release.

**Comment by Alexander-ph** [comment]
> No problems at all! Without knowing the exact releases that are being built, I'm afraid we are unable to help much other than advising to migrate to ROS 2 Humble's release.

I've made it. Yeah!!! Thank you so much!!!
But I'm facing a new problem now, and I have no idea to solve it.
