### ISSUE TITLE
Getting AssertionError when executing python3 -m pip install flask-socketio fastapi uvicorn datamodel_code_generator

### ISSUE THREAD

**Issue by Steven-NYP** [open-rmf/rmf#372]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

22.04

### Open-RMF installation type

Binaries

### Other Open-RMF installation methods

https://github.com/open-rmf/rmf#binary-installation

### Open-RMF version or commit hash

2.3.0

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

When executing python3 -m pip install flask-socketio fastapi uvicorn datamodel_code_generator in rmf setup section (https://github.com/open-rmf/rmf), the following error is received

![image](https://github.com/open-rmf/rmf/assets/37668174/63d94fc9-888f-4deb-a0c9-8fa1462e5984)

Did I missed out anything?

### Steps to reproduce the bug

1. Follow the instruction in rmf setup section (https://github.com/open-rmf/rmf)
2. execute python3 -m pip install flask-socketio fastapi uvicorn datamodel_code_generator
3. datamodel_code_generator will produce the error.

**Comment by aaronchongth** [comment]
Please refrain from posting screenshots of logs or errors, this makes it difficult to search or selectively copy any meaningful text for debugging, use https://gist.github.com/ instead in the future. As of now, we are unable to see error's entire output.

I believe the issue is that the package is called `datamodel-code-generator`, could you try `python3 -m pip install flask-socketio fastapi uvicorn datamodel-code-generator` instead?

**Comment by Steven-NYP** [comment]
Hi @aaronchongth, noted on the screenshot comment.

I have tried the command you suggested, the errors are still the same. The output is as follows
https://gist.github.com/Steven-NYP/b0d86383a9a2322d8cc44ce74ecc60c2

**Comment by aaronchongth** [comment]
Hello @Steven-NYP! After some internal discussions we have decided that the proper fix is to remove `datamodel_code_generator` from the main installation instructions, as it is only used in dev. https://github.com/open-rmf/rmf/pull/375 removes it. You can proceed with the installation without it, `python3 -m pip install flask-socketio fastapi uvicorn`

**Comment by Steven-NYP** [comment]
@aaronchongth, thanks for the update. Installation is working now.
