### ISSUE TITLE
[Other issue]: How to set to come back the charger closest to the finishing point after task "loop"

### ISSUE THREAD

**Issue by miharaka** [open-rmf/rmf#396]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I would like to ask about param "finishing_request" in fleet_adapter.launch.xml. When I give argument "park" to "finishing_request", the robot come back the charger closest to the spawn point. Could I set to come back the charger closest to the point at which the task ends?

**Comment by Yadunund** [comment]
Hi there,

Please ask such questions on our Discussion board.

There is an [API](https://github.com/open-rmf/rmf_ros2/blob/18985da899f0273180af8a17f8406a53d5b4a6da/rmf_fleet_adapter/include/rmf_fleet_adapter/agv/RobotUpdateHandle.hpp#L103) to set the nearest charging waypoint for a robot. If the waypoint is updated using that API before the finishing task begins, the robot should be guided to the new charging waypoint.

**Comment by miharaka** [comment]
@Yadunund , Thank you. I ask the continuation on Discussion board.
