### ISSUE TITLE
[Other issue]: Could not install dependecies using rosdep

### ISSUE THREAD

**Issue by MohammedMuthuFasil** [open-rmf/rmf#482]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I try to install ros humble dependecies using this command "rosdep install --from-paths src --ignore-src --rosdistro humble -y"
but i got this error again.
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rmf_robot_sim_gz_plugins: Cannot locate rosdep definition for [gz_transport_vendor]
rmf_building_sim_gz_plugins: Cannot locate rosdep definition for [gz_transport_vendor]
rmf_building_map_tools: Cannot locate rosdep definition for [gz_fuel_tools_vendor]
rmf_demos_gz: Cannot locate rosdep definition for [gz_sim_vendor]
"  i searched this error but humble does  not have a this type of vendor packages.

**Comment by Yadunund** [comment]
Please re-open a ticket with the bug report template and fill out all details of your setup in the form.

My guess would be that you're trying to build packages with `main` branch checked out on Ubuntu 22.04. We have migrated `main` to Ubuntu 24.04 with support for Rolling and Jazzy distros. If you're building with Humble, please checkout the `humble` branches for each repo.
