### ISSUE TITLE
[Other issue]: Unable to locate package ros-jazzy-rmf-dev

### ISSUE THREAD

**Issue by jabrail-chumakov** [open-rmf/rmf#486]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Just tried to install open-rmf on my Ubuntu 24 with ros jazzy, by faced following error after sudo apt update && sudo apt install ros-jazzy-rmf-dev
:
Unable to locate package ros-jazzy-rmf-dev

Just in case, my ros2 is properly installed, I have amd64. How can I solve it?

**Comment by Yadunund** [comment]
The package will be released for the first time into Jazzy after the next sync: https://discourse.ros.org/t/preparing-for-jazzy-sync-and-patch-release-2024-06-28/38340

**Comment by Yadunund** [comment]
If you want to try it out before the official release, you can test with the pre-release binaries by following instructions here https://docs.ros.org/en/jazzy/Installation/Testing.html and re-runing the install command.

**Comment by jabrail-chumakov** [comment]
@Yadunund So does it mean that it will be released today?

**Comment by Yadunund** [comment]
The date on the post is an estimate and it will be updated once the sync is complete. Please keep an eye out.

**Comment by Yadunund** [comment]
The various distros listed in our README: https://github.com/open-rmf/rmf#installation-instructions

**Comment by jabrail-chumakov** [comment]
@Yadunund Yes, but it's listed there that "jazzi" is supported
![image](https://github.com/open-rmf/rmf/assets/67557966/c8c8f45e-8e1e-4984-bc4a-226ad51edd0b)

**Comment by Yadunund** [comment]
Yes I'm aware and we do support Jazzy. You will find `jazzy` branches on all Open-RMF repos and you can build Open-RMF from source on Jazzy. We've also released binary versions of these packages but they take time to be available on the ROS buildfarm.

See release notes for more information: https://github.com/open-rmf/rmf/releases/tag/release-jazzy-240617 and specifically the
> Note: The binaries will be available after the next Jazzy sync.

**Comment by Yadunund** [comment]
The package should be available after the [recent sync](https://discourse.ros.org/t/new-packages-for-jazzy-jalisco-2024-07-05/38479). Closing this ticket.
