### ISSUE TITLE
Escalation Message/Topic

### ISSUE THREAD

**Issue by arjo129** [open-rmf/rmf#66]
### Description

This was something mentioned by @mxgrey during a conversation. If a robot is not behaving as RMF expects it to we need a standard way to notify the humans :walking: who manage the robot so that there can be some intervention. 

### Implementation considerations

Probably some generic topic, with an error message?  Ideally, we should log such errors to the web dashboard and some log file.

### Alternatives

Hope that robots behave themselves without intervention...

**Comment by cnboonhan** [comment]
pardon noob question: is there some metric that RMF uses to measure how deviant is a robot? how do we decide to alert the Authorities?

**Comment by arjo129** [comment]
There are lot of times where RMF sends a request and expects an Ack message. If there are no ack messages after a fixed timeout, there is probably something wrong...

**Comment by cnboonhan** [comment]
I see. I guess I would learn towards some sort of structured error message (maybe XML?) with fields like <Time>, <Severity>, etc.. so that it's more extensible?

**Comment by matiasbavera** [comment]
If you have to put a number from 1 to 10, being 1 the least important and being 10 the most important, how urgent/important is it to notify the user on the UI that a robot is not behaving as it should.

Should priorities be handled in this type of case? E.g:
* Robot A is not doing anything (priority: Low)
* Robot B is on a loop task (priority: medium)
* Robot C is delivering a cold beer (priority:  high)

If that the case we can measure how invasive the notification should be for the final user.

HTH

**Comment by Yadunund** [comment]
Resolved via https://github.com/open-rmf/rmf_ros2/pull/183
