### ISSUE TITLE
Make a clear separation of public and internal message packages

### ISSUE THREAD

**Issue by mxgrey** [open-rmf/rmf#86]
Right now all of RM's ROS messages are defined by packages inside of [`rmf_internal_msgs`](https://github.com/open-rmf/internal_msgs). These message packages contain many internal messages that are unstable (i.e. their definitions may change at any time to accommodate implementation/design changes). This creates problems for packages downstream of RMF that want to integrate using ROS messages. There are currently no explicitly public, stable messages available for them to tap into.

To fix this issue, we should think very carefully about what the exact inputs and output of an RMF core system should be, and then create explicit, stable public API messages for downstream systems to tap into.

**Comment by Yadunund** [comment]
Closing as [rmf_api_msgs](https://github.com/open-rmf/rmf_api_msgs) was introduced since.
